# Generated by Django 4.2.6 on 2023-11-16 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alertlog', '0004_filterlog_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
